# A clean, informative prompt for all shells

"$schema" = 'https://starship.rs/config-schema.json'

format = """
[<](color_orange)\
$os\
$shell\
$username\
[|](bg:color_yellow fg:color_orange)\
$directory\
[|](fg:color_yellow bg:color_aqua)\
$git_branch\
$git_status\
[|](fg:color_aqua bg:color_blue)\
$c\
$cpp\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[|](fg:color_blue bg:color_bg3)\
$docker_context\
$conda\
$pixi\
[|](fg:color_bg3 bg:color_bg1)\
$time\
[>](fg:color_bg1)\
$line_break$character"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

# Prompt character changes based on success/failure
[character]
disabled = false
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red)"
vicmd_symbol = "[⮜](bold yellow)"
vimcmd_replace_one_symbol = '[r](bold fg:color_purple)'
vimcmd_replace_symbol = '[r](bold fg:color_purple)'
vimcmd_visual_symbol = '[v](bold fg:color_yellow)'

[os]
disabled = false
style = "bg:color_orange fg:color_fg0"

[os.symbols]
Windows = "WIN"
Ubuntu = "UBU"
SUSE = "SUSE"
Raspbian = "PI"
Mint = "MINT"
Macos = "MAC"
Manjaro = "MANJARO"
Linux = "LINUX"
Gentoo = "GENTOO"
Fedora = "FEDORA"
Alpine = "ALPINE"
Amazon = "AWS"
Android = "ANDROID"
Arch = "ARCH"
Artix = "ARTIX"
EndeavourOS = "ENDEAVOUR"
CentOS = "CENTOS"
Debian = "DEBIAN"
Redhat = "RHEL"
RedHatEnterprise = "RHEL"
Pop = "POP"

[shell]
disabled = false
format = "[ $indicator ]($style)"
style = "bold white"

[username]
show_always = true
style_user = "bg:color_orange fg:color_fg0"
style_root = "bg:color_orange fg:color_fg0"
format = "[ $user ]($style)"

[hostname]
ssh_only = true
format = "[@$hostname]($style) "
style = "bold green"

[directory]
style = "fg:color_fg0 bg:color_yellow"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = ".../"

[directory.substitutions]
"~" = "🏠"
"Documents" = "📄"
"Downloads" = "📥"
"Pictures" = "🖼️"
"Developer" = "💻"

[git_commit]
commit_hash_length = 4
tag_symbol = '🔖 '

[git_branch]
symbol = '🌱 '
truncation_length = 4
truncation_symbol = ''
ignore_branches = ['master', 'main']
style = "bg:color_aqua"
format = '[[ $symbol $branch ](fg:color_fg0 bg:color_aqua)]($style)'

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = '[🍒 PICKING](bold red)'

[git_status]
conflicted = '🏳'
up_to_date = '✓'
untracked = '🤷'
stashed = '📦'
modified = '📝'
staged = '[++\($count\)](green)'
renamed = '👅'
deleted = '🗑'
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
windows_starship = '/mnt/c/Users/mjpa/scoop/apps/starship/current/starship.exe'
style = "bg:color_aqua"
format = '[[($all_status$ahead_behind )](fg:color_fg0 bg:color_aqua)]($style)'


[nodejs]
symbol = "⬢ "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[c]
symbol = "C"
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[rust]
symbol = "🦀 "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[golang]
symbol = "go"
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[php]
symbol = "php"
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[java]
symbol = "java"
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[kotlin]
symbol = "kt"
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[haskell]
symbol = "hs"
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[python]
symbol = "🐍 "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[docker_context]
symbol = "docker"
style = "bg:color_bg3"
format = '[[ $symbol( $context) ](fg:#83a598 bg:color_bg3)]($style)'

[conda]
style = "bg:color_bg3"
format = '[[ $symbol( $environment) ](fg:#83a598 bg:color_bg3)]($style)'

# Performance optimizations
[cmd_duration]
min_time = 2_000
format = "took [$duration]($style) "
style = "bold yellow"

[battery]
disabled = true

[time]
disabled = false
time_format = "%R"
style = "bg:color_bg1"
format = '[[ ⏰ $time ](fg:color_fg0 bg:color_bg1)]($style)'

[aws]
disabled = true

[gcloud]
disabled = true

[package]
disabled = true

[line_break]
disabled = false
